# Setup
remote_theme: rosario/kasper

name: prafesar.github.io
description: Blogging about stuffs
meta_description: "Your New Jekyll Site, Blogging about stuffs"

markdown: kramdown
highlighter: rouge
logo: true
paginate: 10
# baseurl: /kasper
domain_name: "http://prafesar.github.io"
# google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "Prafesar"

# Disqus config
disqus-shortname: ""